import "@/app/css/globals.css";

import { Inter } from "next/font/google";
import { ThemeProvider } from "./theme-provider";
import Header from "@/components/ui/header";
import Footer from "@/components/ui/footer";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

// const aspekta = localFont({
//   src: [
//     {
//       path: "../public/fonts/Aspekta-500.woff2",
//       weight: "500",
//     },
//     {
//       path: "../public/fonts/Aspekta-650.woff2",
//       weight: "650",
//     },
//   ],
//   variable: "--font-aspekta",
//   display: "swap",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* suppressHydrationWarning: https://github.com/vercel/next.js/issues/44343 */}
      <body
        className={`${inter.variable} font-inter antialiased bg-background text-foreground tracking-tight`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="max-w-7xl mx-auto">
            <div className="min-h-screen flex">
              {/* <SideNavigation /> */}

              {/* Main content */}
              <main className="grow overflow-hidden px-6">
                <div className="w-full h-full max-w-[1072px] mx-auto flex flex-col">
                  <Header />

                  {children}
                  <Footer />
                </div>
              </main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
